### ISSUE TITLE
No notification with Pebble watch

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1141]
reported by Vurpo and Jon 😺

It seems that extra settings must be set 

08:49:04.639 [Binder_2] INFO  n.f.g.e.NotificationListener - Processing notification from source im.vector.alpha with flags: 512

08:49:04.641 [Binder_2] INFO  n.f.g.e.NotificationListener - Not forwarding notification, FLAG_GROUP_SUMMARY is set and no wearable action present. Notification flags: 512

**Comment by ylecollen** [comment]
Reported by Vurpo

It seems like the notifications I get from Telegram (for comparison) have some sort of "wearable action":
09:05:40.058 [Binder_2] INFO  n.f.g.e.NotificationListener - Processing notification from source org.telegram.messenger with flags: 16

09:05:40.073 [Binder_2] INFO  n.f.g.e.NotificationListener - found wearable action: Reply to hackbot  null

**Comment by ylecollen** [comment]
https://developer.android.com/training/wearables/notifications/creating.html

**Comment by tradej** [comment]
+1 on this. Multiple users and wearables are affected by this (see the linked bug above). Thank you.

**Comment by edam** [comment]
FWIW, notifications used to work, with basic system notifications being sent to wearables. They stopped working around riot 0.8.1 (f-droid), although whether this was due to a riot change or an android/wear os change is unclear.

**Comment by eras** [comment]
It seems the linked issue explains everything, but in the off-chance it doesn't, here's a system where it seems to work:

- Riot 0.8.5 (G-#130)
- Wear OS 2.10.0.188560295.gms

Apparently it was fixed with 0.8.5, as I have a confirmation of it not working with 0.8.4 but working after updating to 0.8.5.

**Comment by tradej** [comment]
Notifications still do not work on Mi Band 2 (using GadgetBridge).

* Riot 0.8.10 (F-10c3e522)
* Mi Band 2 FW: 1.0.1.54
* Android 8.1.0
* Nokia 5

**Comment by tradej** [comment]
I have done some digging and it seems like what's necessary is to add a `NotificationCompat.WearableExtender` instance to the notification that extends the notification when it's built. This instance should have an action added on it, which is what GadgetBridge processes.

I've looked at Telegram, and they seem to do it this way:

* Creating a [`weaRreplyAction`](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/f2cdfecef789cd51d427232e94ad2ef6efa91a71/TMessagesProj/src/main/java/org/telegram/messenger/NotificationsController.java#L2049)
* Adding the `wearReplyAction` to the [`wearableExtender`](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/f2cdfecef789cd51d427232e94ad2ef6efa91a71/TMessagesProj/src/main/java/org/telegram/messenger/NotificationsController.java#L2096)
* Extending the [notification](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/f2cdfecef789cd51d427232e94ad2ef6efa91a71/TMessagesProj/src/main/java/org/telegram/messenger/NotificationsController.java#L2123) with the `wearableExtender`

Can a developer please have a look at this? I've only got basic Java skills and I'm quite lost in the code base. Thank you very much.

**Comment by h3ndrik** [comment]
There is some code in NotificationUtils.kt which seems to add the wearableExtender at least in one case here:

https://github.com/vector-im/riot-android/blob/3a650e15fe4edd79b1f5326f95fba312dad168f7/vector/src/main/java/im/vector/notifications/NotificationUtils.kt#L512

**Comment by h3ndrik** [comment]
issue seems to be fixed (or worked-around) in Gadgetbridge 0.31.0.

**Comment by swedneck** [comment]
I can also confirm that the gadgetbridge update makes it work!
