### ISSUE TITLE
The notification counter isn't correct

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1309]
reported by  @b0b:matrix.org
The notification counter isn't correct. It indicates 1 whereas I read all messages. I'm using a updated zte axon 7 with nova launcher, but I had the same problem with my previous phone on Android 6.

https://github.com/matrix-org/riot-android-rageshakes/issues/291

**Comment by Matrixcoffee** [comment]
Perhaps the same as vector-im/riot-web#4336?

**Comment by ylecollen** [comment]
The android client computes this value with the synced counters.
https://github.com/vector-im/riot-android/blob/develop/vector/src/main/java/im/vector/Matrix.java#L121

it seems being the same issue than MatrixCoffee reported.

**Comment by sabrinaj** [comment]
Has been fixed: https://github.com/matrix-org/matrix-android-sdk/pull/181

**Comment by BobVul** [comment]
I seem to still have this problem with an up-to-date Nova Launcher and TeslaUnread.

The badge is on `2` when everything is read, and goes up from there (`3` with 1 unread, etc.).

Not sure if this is related to a room invite I rejected.

Is there any way I can provide more information?
