### ISSUE TITLE
F-droid release incompatible: INSTALL_FAILED_NO_MATCHING_ABIS

### ISSUE THREAD

**Issue by jjakob** [vector-im/riot-android#3483]
The last release from F-droid that was compatible with Android 7 is 0.7.11.
The app now shows "incompatible" and is unable to installon Android 7.1.2.

**Comment by wchen342** [comment]
Same on LineageOS 16, Sony XZ1. The error code is 113: INSTALL_FAILED_NO_MATCHING_ABIS. It seems native code is compiled with wrong architecture.

**Comment by jjakob** [comment]
> Same on LineageOS 16, Sony XZ1. The error code is 113: INSTALL_FAILED_NO_MATCHING_ABIS. It seems native code is compiled with wrong architecture.

LOS 16 is Android 9.0, so it's obviously not just 7. I'll correct the issue title.

**Comment by jjakob** [comment]
My kernel shows armv8l, phone should be arm64.

**Comment by ghost** [comment]
I have the same problem on Android 10. I couldn't update Riot.im and now F-Droid shows all the older versions are incompatible too...

**Comment by Termuellinator** [comment]
can confirm the issue on mido / microG-LOS16, RiotX works in the meantime.

**Comment by Bubu** [comment]
There was a problem with the fdroid metadata, where accidentally some of the abi versions where put into the archive instead of the main repo. It'll be fixed with the next fdroid index update (hopefully tomorrow).

**Comment by Bubu** [comment]
This should be fixed (since a week or so)

**Comment by jjakob** [comment]
Can confirm it was fixed. Upgrading went fine on my device.

**Comment by maisiliymBridj** [comment]
This issue is not fixed on 0.9.12 which is the latest f-droid release. The rom is fresh LOS17.1 from yesterday.
