### ISSUE TITLE
Notifications doesn't work using Google Play version

### ISSUE THREAD

**Issue by sim6** [vector-im/riot-android#995]
Hello,

Some people are reporting that notifications doesn't work with version 0.6.8 from Google Play.

https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$14887357281503041DbPaP:matrix.org

Thanks.

**Comment by Damianuscz** [comment]
Proved

On Samsung S7 (flat) android 7 and nexus 7 2013 with andorid 6 same problem with last google app version. Notification did not work!  Reinstal or erase data same result. On both devices RIOT app be blacklisted in powersave solution (doze etc..) After remove and install version from F-droid noficication will work.

**Comment by xaviot** [comment]
Hi there
I've been checking how notification works on my device (Samsung Galaxy S6) as I was having problems with Play and Fdroid versions.

Symptoms Fdroid version:
- No notifications at all until I open (junt once) Riot once mobile is on.

Symptoms Play Store version:
- No notifcation never, only when Riot was opened manually

Testing Fdroid Version (not solved)
I uninstalled Fdroid version and cleared cache. I confirmed that mobile was not blocking notifications due to battery issues and Riot was allowed to notify. I restared and no way to get it working. Alwasy the same. Once you open (once) riot it notifes ok but first time has to be opened manually.


Testing Play Store version (solved)
1.- Uninstall Riot (Play version, of course)
2.- Clear mobile cache (storege > clear cache)
3.- Restart mobile 
4.- Install  Riot (Play Store version)
5.- Clear cache mobile (again)
6.- Login Riot (mobile)
7.- Restart mobile (yes... again)
8.- Notification start arriving (R on top bar)
NOTE: i'm sure that some steps may not be necessary

So, now, I'm using Play Store Version which is able to notify simultaniously using web client (riot.im) and mobile (notification sound).

I hope it helps to improve Riot as I'm sure no so many people will do what i've done.

thanks for your work

**Comment by xaviot** [comment]
![2017-03-07 12_29_52-riot 1](https://cloud.githubusercontent.com/assets/26248862/23654619/d0ce8eb4-0331-11e7-971c-cfd32b065ace.png)

Here you are how I've configured (web client) notification options

**Comment by xaviot** [comment]
Fdrodi issue is related to 
https://github.com/vector-im/riot-android/issues/319

**Comment by ylecollen** [comment]
@xaviot ,

First at all, thank you for your help and your time.

The fdroid version needs to be launched once to receive notification.

The google play version seems to do not receive pushes. Did you test with our develop version or the google play one.
I already met such issue but i never found out why it failed.
I suspect that the GCM token is no more valid.
I improved it on the develop version (http://matrix.org/jenkins/job/VectorAndroidDevelop/).
The GCM token was kept even after a logout. 
By now, the GCM token is renewed after a logout or a clear application cached.

**Comment by xaviot** [comment]
Hi there,
I think I've explained bad. Now, with Play version it's everything working fine, prior clearing all cache's

thanks for your answer

**Comment by zzottel** [comment]
I had such a case yesterday evening with the stable version from Play Store. I never had problems there yet, but yesterday evening there should have been two notifications, and both didn't arrive, neither at my device (BQ Aquaris X5 plus) nor at my wife's (Samsung Galaxy S5 mini).

Are there intermittent failures if something at matrix.org is down? Or should notifications be delivered later in such a case?

**Comment by alugarius** [comment]
I have this problem right now, version 0.6.9

**Comment by alugarius** [comment]
@ylecollen 
I will follow the guide of @xaviot and try if it's working.
I have an Wiko Robby with Android 6

**Comment by szimszon** [comment]
Hi,

Thanks for the great app! I consider to replace Signal with Riot but with version 0.6.12 (gp-787c09b2) I also don't get any notification in my phone. Android version 4.4.4 (vanilla GT-I9195I) and Android 6.0.1 (SM-A300FU)

**Comment by szimszon** [comment]
Hm, not all notification is missing. Sometimes I receive invite notifications with delay... :-o

**Comment by ylecollen** [comment]
@szimszon 
It is weird : i don't have such issues on my side.

-> do you have notification when the application is opened ?
-> could you send a bug report if you don't have them ?

**Comment by szimszon** [comment]
@ylecollen 
Yes I have prompt notifications if the application is open.

I'll try to test it again and  will send a bug report...

**Comment by szimszon** [comment]
I made some test yesterday.
And I have to say that it works but unreliable. I can't find a pattern. Sometimes I don't even get invite notifications. Yesterday afternoon notifications worked. After some time I experienced 4-6min delay after that it stopped working. In the morning I got invite notifications. Than again nothing.

Before yesterday it was trickier because I was in the same room with my desktop client, but not anymore after I learned that notification could be suppressed if read notification is sent by another client.

**Comment by szimszon** [comment]
I made some test yesterday.
And I have to say that it works but unreliable. I can't find a pattern. Sometimes I don't even get invite notifications. Yesterday afternoon notifications worked. After some time I experienced 4-6min delay after that it stopped working. In the morning I got invite notifications. Than again nothing.

Before yesterday it was trickier because I was in the same room with my desktop client, but not anymore after I learned that notification could be suppressed if read notification is sent by another client.

**Comment by benhubert** [comment]
I can confirm some problems with the notifications when using the Google Play version. I have two devices (One Plus One, Android 6.0.1), both with the same problem:

 * I *do* receive notifications in the notification bar (always)
 * but I don't get any notification sound when using the Google Play app.

I debugged this a lot now, but with the debug-build the phone plays the default notification sound when receiving a message. So debugging is very hard, because this problem seems to exist only for the Play version.

**Comment by alugarius** [comment]
@benhubert 
What is your second device?

**Comment by benhubert** [comment]
Both devices are One Plus One, Android 6.0.1.

**Comment by Mikaela** [comment]
I think I sent multiple rageshakes about this today.

OnePlus 3, Android 7.1.1.

**Comment by ylecollen** [comment]
Guys,

could you tell me if you disabled the background sync ?
i fixed this issue https://github.com/vector-im/riot-android/issues/1546 this morning

**Comment by ylecollen** [comment]
@benhubert 
The notification sound has been fixed on the develop version i.e >= 0.7.1.

@szimszon 
i've the background sync management (for the fdroid version) but you might need to increase the delay between syncs;

**Comment by benhubert** [comment]
@ylecollen No, I don't have background sync disabled. It's enabled on both of my OnePlus One's. One device is running 0.7.01 already but the notification sound is still not played on this phone.

**Comment by benhubert** [comment]
@ylecollen I also installed the F-Droid version now on one of the devices but with no success. I still don't get notified. Additionally, sometimes I don't even get the notification. I have to open the app and then the messages arrive.

**Comment by benhubert** [comment]
After some debugging I found out that the `bingRule` I got with the `MXEventListener.onBingEvent` did not contain the `sound` tweak. So I searched for the problem on the server side and found out, that in the notification configuration for `Messages in group chats` was set to `On` but not to `Noisy`

![selection_010](https://user-images.githubusercontent.com/4912084/30712772-6eaf9ce6-9f0d-11e7-83fd-1489290f5453.png)

Why was the notification sound played when I debugged this on June 27th? Because I created a test room with only two people, so the setting that was applied back then was `Messages in one-to-one chats`.

Why did it work until June for me? Because my chats contained only two people, but in mid of June I added more to the chat.

So, works for me :white_check_mark:

**Comment by Lachlan-uts** [comment]
So I've encountered a similar, basically an extension of this problem. What I've discovered is if I have noisy notifications enabled on my web ui, upon receiving a notification the app will crash. If I have notifications just on, all is fine however (aside from no notification noise obviously).

This is how I currently have my notifications setup to try and avoid crashes whilst still having sound on my desktop app.

![notifications](https://user-images.githubusercontent.com/31094273/32583809-33f18470-c541-11e7-9ff6-4b7ab38d417e.png)

The phone I'm using is called a Redmi Note 4X by Xiaomi, running android version 7.0 NRD90M. I've already sent crash logs when this issue has occurred, however if there's any more information I can give, please let me know.

**Comment by eggsperde** [comment]
I use a (Xiaomi) Honor 6X and is not vanilla Android and I did not get any notifications. Turns out, in the battery section of settings there is a menu to "close apps after screen lock" and, how else could it be, I barely got notifications. Now it seems to work fine though. I'll keep an eye out for anomalies and report back if necessary. Merry Christmas!

**Comment by r4dh4l** [comment]
Hi,

I've convinced a lot of friends to use Riot but unfortunately some of them don't get push notifications. What is the best way to provide information helping to fix this issue?
Is a rage shake with the info text `notifications missing issue 995` enough or do you need more information here or in https://github.com/vector-im/riot-ios/issues/1696 (the rage shake feature seems to be a nice way to provide information but as user you don't have any idea if the rage shake was helpful for the person "in charge" )?

My question is about which information I can provide the users in my area if they are affected so they can provide really helpful debug information.

**Comment by echto** [comment]
@r4dh4l, notifications are fixed in Version 0.8.22.

**Comment by r4dh4l** [comment]
Thx @echto ! :+1:
